# Generated by Django 4.2 on 2023-05-20 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packName', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('theme', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('title_img', models.ImageField(upload_to='')),
                ('files_id', models.IntegerField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 5, 20, 10, 0, 51, 829345))),
            ],
        ),
    ]
