# Generated by Django 4.2 on 2023-06-14 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCreator', models.CharField(max_length=255)),
                ('userCreatorID', models.CharField(max_length=255)),
                ('setName', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 22, 33, 3, 781706))),
            ],
        ),
        migrations.AlterField(
            model_name='graphicpack',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 22, 33, 3, 780708)),
        ),
    ]
